experiment_name: femt_instance_seg
run_name: 3minute_no_anisotropy
task_name: train
tags:
    - dev
train: true
test: false
ckpt_path:
seed: 12345
data:
    _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
    data:
    transforms:
        - _target_: monai.transforms.LoadImaged
          keys:
              - ${source_col}
          reader:
              - _target_: cyto_dl.image.io.MonaiBioReader
                dimension_order_out: CZYX
        - _target_: monai.transforms.NormalizeIntensityd
          keys: ${source_col}
        - _target_: monai.transforms.ToTensord
          keys:
              - ${source_col}
          dtype: float16
        - _target_: monai.transforms.SpatialPadd
          keys: ${source_col}
          spatial_size: [13, -1, -1]
          method: "end"
          mode: "replicate"
    _aux:
        patch_shape:
            - 12
            - 192
            - 192
    num_workers: 1
    batch_size: 1
    pin_memory: true
    persistent_workers: false

model:
    _target_: cyto_dl.models.im2im.MultiTaskIm2Im
    save_images_every_n_epochs: 1
    save_dir: ${paths.output_dir}
    x_key: ${source_col}
    backbone:
        _target_: cyto_dl.nn.vits.Seg_ViT
        spatial_dims: 3
        base_patch_size:
            - 4
            - 8
            - 8
        num_patches:
            - 3
            - 24
            - 24
        emb_dim: 768
        decoder_layer: 3
        encoder_ckpt: //allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/cross_mae/EMT_pretrain/2024-03-04_15-05-33/checkpoints/epoch_1289.ckpt
        freeze_encoder: true
        n_decoder_filters: 32
        upsample_factor:
            - 1
            - 1
            - 1
        num_layer: 12
        num_head: 12
        context_pixels:
            - 2
            - 4
            - 4
    task_heads: ${kv_to_dict:${model._aux._tasks}}
    optimizer:
        generator:
            _partial_: true
            _target_: torch.optim.AdamW
            weight_decay: 0.05
    lr_scheduler:
        generator:
            _partial_: true
            _target_: torch.optim.lr_scheduler.OneCycleLR
            max_lr: 0.0005
            epochs: ${trainer.max_epochs}
            steps_per_epoch: 1
            pct_start: 0.05
    inference_args:
        sw_batch_size: 1
        roi_size: ${data._aux.patch_shape}
        overlap: 0.25
        mode: gaussian
    _aux:
        _tasks:
            - - ${target_col}
              - _target_: cyto_dl.nn.BaseHead
                loss:
                    _target_: cyto_dl.models.im2im.utils.InstanceSegLoss
                    dim: 3
                    weights:
                        skeleton: 10
                        semantic: 10
                        boundary: 10
                        vector: 100
                save_input: true
                postprocess:
                    input:
                        _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
                        dtype: numpy.float32
                    prediction:
                        _target_: cyto_dl.models.im2im.utils.instance_seg.InstanceSegCluster
                        anisotropy: 1
                        skel_threshold: -4.0
                        semantic_threshold: -7
trainer:
    _target_: lightning.Trainer
    default_root_dir: ${paths.output_dir}
    min_epochs: 1
    max_epochs: 300
    accelerator: gpu
    devices:
        - 0
    precision: 16
    check_val_every_n_epoch: 10
    deterministic: false
    detect_anomaly: false
    gradient_clip_val: 10
paths:
    root_dir: ${oc.env:PROJECT_ROOT, './'}
    data_dir: ${paths.root_dir}/data/
    log_dir: ${paths.root_dir}/logs/
    output_dir: ${hydra:runtime.output_dir}
    work_dir: ${hydra:runtime.cwd}
extras:
    ignore_warnings: true
    enforce_tags: false
    print_config: false
    precision:
        _target_: torch.set_float32_matmul_precision
        precision: medium
source_col: raw
target_col: seg
persist_cache: true
