experiment_name: flexi_mae
run_name: small_encoder_curated_data_no_offset_aug
task_name: train
tags:
- dev
train: true
test: False
ckpt_path: 
seed: 12345
semantic_thresh: 
data:
    _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
    data:
    transforms:
        - _target_: monai.transforms.LoadImaged
          keys:
              - ${source_col}
          reader:
              - _target_: cyto_dl.image.io.MonaiBioReader
                dimension_order_out: CZYX
                C: 0
                dask_load: False
        - _target_: monai.transforms.NormalizeIntensityd
          keys: ${source_col}
        - _target_: monai.transforms.ToTensord
          keys:
              - ${source_col}
          dtype: float16
    _aux:
        patch_shape:
            - 24
            - 192
            - 192
    num_workers: 0
    batch_size: 1
    pin_memory: true
    persistent_workers: false
model:
  _target_: cyto_dl.models.im2im.MultiTaskIm2Im
  save_images_every_n_epochs: 1
  save_dir: ${paths.output_dir}
  x_key: ${source_col}
  backbone:
    _target_: cyto_dl.nn.vits.Seg_ViT
    spatial_dims: 3
    base_patch_size:
    - 4
    - 8
    - 8
    num_patches:
    - 6
    - 24
    - 24
    emb_dim: 256
    encoder_ckpt: //allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/cross_mae/small_pretrain/2024-03-24_21-15-03/checkpoints/last.ckpt
    freeze_encoder: true
    n_decoder_filters: 512
    n_intermediate_weights: 4
    num_layer: 12
    num_head: 8
    context_pixels:
    - 2
    - 4
    - 4
  task_heads: ${kv_to_dict:${model._aux._tasks}}
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.AdamW
      lr: 0.0003
      weight_decay: 0.05
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.99
  inference_args:
    sw_batch_size: 1
    roi_size: ${data._aux.patch_shape}
    overlap: 0.16
    mode: gaussian
    progress: True
  _aux:
    _tasks:
    - - ${target_col}
      - _target_: cyto_dl.nn.BaseHead
        loss:
          _target_: cyto_dl.models.im2im.utils.InstanceSegLoss
          dim: 3
          weights:
            semantic: 110
            boundary: 10
        save_input: true
        postprocess:
          input:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            dtype: numpy.float32
          prediction:
            # _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            # dtype: numpy.float32
            _target_: cyto_dl.models.im2im.utils.instance_seg.InstanceSegCluster
            dim: 3
            min_size: 100
            skel_threshold: 0
            semantic_threshold: ${semantic_thresh}
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 300
  accelerator: gpu
  devices:
  - 0
  precision: 16
  check_val_every_n_epoch: 10
  deterministic: false
  detect_anomaly: false
  max_time: null
  gradient_clip_val: 10
paths:
  root_dir: ${oc.env:PROJECT_ROOT, './'}
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: true
  enforce_tags: False
  print_config: true
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
source_col: lr
target_col: nucseg
persist_cache: true
