experiment_name: cytodata_models
run_name: nuc_iseg
task_name: train
tags:
- dev
train: true
test: false
ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/cytodata_models/nuc_iseg/2023-10-06_09-30-27/checkpoints/last.ckpt"
seed: 12345
data:
  _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
  data: null
  transforms:
  - _target_: monai.transforms.LoadImaged
    keys:
    - ${source_col}
    reader:
    - _target_: cyto_dl.image.io.MonaiBioReader
      dimension_order_out: CZYX
  - _target_: monai.transforms.NormalizeIntensityd
    keys: ${source_col}
  - _target_: cyto_dl.image.transforms.clip.Clipd
    keys: ${source_col}
    low: -7
    high: 7
    percentile: false
  _aux:
    patch_shape:
    - 48
    - 384
    - 384
  
  num_workers: 1
  batch_size: 1
  pin_memory: true
  persistent_workers: false
model:
  _target_: cyto_dl.models.im2im.MultiTaskIm2Im
  save_images_every_n_epochs: 1
  x_key: ${source_col}
  save_dir: ${paths.output_dir}
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: 32
    strides:
    - 1
    - 2
    - 1
    - 2
    - 2
    kernel_size:
    - 3
    - 3
    - 1
    - 3
    - 3
    upsample_kernel_size:
    - 2
    - 1
    - 2
    - 2
    dropout: 0.0
    res_block: true
  task_heads:
    nucseg:
      _target_: cyto_dl.nn.ResBlocksHead
      in_channels: 32
      out_channels: 6
      resolution: lr
      dense: true
      n_convs: 2
      save_raw: true
      loss:
        _target_: cyto_dl.models.im2im.utils.skoots.SkootsLoss
        dim: 3
      postprocess:
        input:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          ch: -1
          dtype: numpy.float32
        prediction:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          ch: 1
          threshold: 1
          label: true
          dtype: numpy.uint8
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.AdamW
      lr: 0.0001
      weight_decay: 0.001
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.CosineAnnealingLR
      T_max: ${trainer.max_epochs}
      eta_min: 5.0e-05
  inference_args:
    roi_size: ${data._aux.patch_shape}
    sw_batch_size: 1
    overlap: 0.25
    mode: gaussian
    progress: True
callbacks:
logger:
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 1000
  accelerator: gpu
  devices:
  - 0
  check_val_every_n_epoch: 50
  deterministic: false
  detect_anomaly: false
  precision: 16
  num_sanity_val_steps: 1
paths:
  root_dir: .
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: true
  enforce_tags: false
  print_config: false
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
source_col: hr
target_col: nucseg
persist_cache: true
