working_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/validation/cytodata/${deployment_name}
deployment_name: nucleus_iseg

local_run: True

steps:
    - function: morflowgenesis.steps.image_object_from_csv.generate_objects
      args:
        csv_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/data/paired_dataset_tf_lf/seg/test.csv"
        working_dir: ${working_dir}
        source_column: hr
      step_type: "init"

    # run segmentation from 100x lamin
    - function: morflowgenesis.steps.run_cytodl_gather.run_cytodl
      args:
        output_name: 100x_lamin_seg
        input_step: generate_objects_hr
        config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/cellnucmorph_cytodata/nucleus_iseg_validation/model.yaml
      step_type: "gather"

    # watershed on real lamin
    - function: morflowgenesis.steps.segmentation_seeded_watershed.run_watershed
      args:
        output_name: real_lamin
        raw_input_step: generate_objects_hr
        seg_input_step: run_cytodl_100x_lamin_seg
        mode: 'erosion'
        erosion: 5
        include_edge: False

    - function: morflowgenesis.steps.single_cell_dataset.single_cell_dataset
      args:
          output_name: cells
          splitting_step: run_watershed_real_lamin
          raw_steps: [generate_objects_hr]
          raw_steps_rename: [100x_lamin]
          seg_steps: [run_cytodl_100x_lamin_seg, run_watershed_real_lamin]
          seg_steps_rename: [pred, gt]
          mask: False
          keep_lcc: True

    - function: morflowgenesis.steps.feature_calculation.calculate_features
      args:
        output_name: features
        input_step: single_cell_dataset_cells
        features:
            - height
            - volume
            - shcoeff
            
    - function: morflowgenesis.steps.segmentation_mesh.mesh
      args:
        output_name: mesh
        segmentation_steps: [run_cytodl_100x_lamin_seg]
        resize: [0.53, 0.2, 0.2]

    - function: morflowgenesis.steps.pca.run_pca
      args:
        output_name: pca
        feature_step: calculate_features_features
        features_regex: '.*shcoeffs.*'
        calculate_name: gt
        apply_names: [pred]
      step_type: 'gather'
        

    - function: morflowgenesis.steps.plot.run_plot
      args:
        output_name: plot
        input_step: calculate_features_features
        features: [volume, height]
        label:
          segmentation_name: gt
          description: 'Watershed GT'
        pred:
          - segmentation_name: pred
            description: Nucmorph Seg on NucMorph TF Lamin
      step_type: 'gather'

    - function: morflowgenesis.steps.plot.run_plot
      args:
        output_name: pca_plot
        input_step: run_pca_pca
        features: [PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10]
        label:
          segmentation_name: gt
          description: 'Watershed GT'
        pred:
          - segmentation_name: pred
            description: Nucmorph Seg on NucMorph TF Lamin
      step_type: 'gather'