align_segmentations_to_image:
    function: morflowgenesis.steps.align_segmentations_to_image
    # all variables passed that aren't "function" or "task_runner" are assumed to be args
    image_step:
    segmentation_step:
    optional boundary: False
