run_pca:
    function: morflowgenesis.steps.run_pca
    # all variables passed that aren't "function" or "task_runner" are assumed to be args
    output_name: pca
    feature_step: calculate_features/single_cell_dataset
    features_regex:
    calculate_name:
    apply_names:
    n_components: 10
