run_cytodl:
    function: morflowgenesis.steps.run_cytodl
    # all variables passed that aren't "function" or "task_runner" are assumed to be args
    input_step:
    config_path:
    output_name:
    run_id:
    checkpoint_path:
