defaults:
    - segmentation_contact_sheet_task_runner: ../../../task_runner/dask

segmentation_contact_sheet_task_runner:
    task_limit: 5

segmentation_contact_sheet:
    task_runner: ${..segmentation_contact_sheet_task_runner}
    function: morflowgenesis.steps.segmentation_contact_sheet
    # all variables passed that aren't "function" or "task_runner" are assumed to be args
    output_name: segmentation_contact_sheet
    single_cell_dataset_step:
    feature_step:
    segmentation_name:
    x_feature:
    y_feature:
    raw_name:
    n_bins: 10
    seg_names: []
