defaults:
    - single_cell_dataset_task_runner: ../../../task_runner/dask

single_cell_dataset_task_runner:
    task_limit: 150
    memory_limit: 500Gi
    processes: True

single_cell_dataset:
    task_runner: ${..single_cell_dataset_task_runner}
    function: morflowgenesis.steps.single_cell_dataset
    output_name: single_cell_dataset
    splitting_step:
    seg_steps:
    seg_steps_rename:
    raw_steps: []
    raw_steps_rename:
    input_res:
    out_res:
    padding: [10, 25, 25]
    mask: True
    keep_lcc: False
    iou_thresh:
    include_edge_cells: True
    features:
    save: True
