defaults:
    - split_image_task_runner: ../../../task_runner/dask

split_image_task_runner:
    task_limit: 200
    memory_limit: 125Gi
    # this might not be optimal since image splitting is io limited
    processes: True

split_image:
    task_runner: ${..split_image_task_runner}
    function: morflowgenesis.steps.split_image
    image_path:
    channels:
    working_dir:
    output_name: split_image
    dimension_order_out: CZYX
    timepoints: -1
    scenes: -1
