model:
    _target_: cyto_dl.models.im2im.MultiTaskIm2Im
    save_images_every_n_epochs: 1
    x_key: raw
    save_dir: null
    compile: False
    hr_skip:
        _target_: monai.networks.blocks.Upsample
        spatial_dims: 3
        in_channels: 1
        out_channels: 32
        scale_factor:
            - 2.6134
            - 2.5005
            - 2.5005
        mode: nontrainable
    backbone:
        _target_: monai.networks.nets.DynUNet
        spatial_dims: 3
        in_channels: 1
        out_channels: 32
        strides:
            - 1
            - 2
            - 1
            - 2
            - 1
            - 2
        kernel_size:
            - 3
            - 3
            - 3
            - 3
            - 3
            - 3
        upsample_kernel_size:
            - 2
            - 1
            - 2
            - 1
            - 2
        dropout: 0.0
        res_block: true
        filters:
            - 96
            - 192
            - 288
            - 384
            - 480
            - 576
    task_heads:
        nucseg:
            _target_: cyto_dl.nn.ResBlocksHead
            in_channels: 32
            out_channels: 6
            resolution: hr
            dense: true
            n_convs: 3
            upsample_method: nontrainable
            upsample_ratio:
                - 2.6134
                - 2.5005
                - 2.5005
            loss:
                _target_: cyto_dl.models.im2im.utils.skoots.SkootsLoss
                dim: 3
            postprocess:
                prediction:
                    _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
                    ch: 1
                    threshold: 2.23
                    dtype: numpy.uint16
                    label: True
    optimizer:
        generator:
            _partial_: true
            _target_: torch.optim.AdamW
            lr: 0.0001
            weight_decay: 0.001
    lr_scheduler:
        generator:
            _partial_: true
            _target_: torch.optim.lr_scheduler.CosineAnnealingLR
            T_max: 300
            eta_min: 5.0e-05
    inference_args:
        roi_size:
            - 24
            - 128
            - 128
        sw_batch_size: 1
        overlap: 0.25
        mode: gaussian
model/params/total: 85531558
model/params/trainable: 85531558
model/params/non_trainable: 0
data:
    _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
    data: null
    transforms:
        - _target_: monai.transforms.LoadImaged
          keys:
              - raw
          reader:
              - _target_: cyto_dl.image.io.MonaiBioReader
                dimension_order_out: ZYX
                C: 0
        - _target_: monai.transforms.AddChanneld
          keys: raw
        - _target_: monai.transforms.NormalizeIntensityd
          keys: raw
    num_workers: 1
    batch_size: 1
    pin_memory: true
    persistent_workers: false
trainer:
    _target_: lightning.Trainer
    default_root_dir: /allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/skoots/finetune_MEC/2023-09-28_09-21-37
    min_epochs: 1
    max_epochs: 300
    accelerator: gpu
    devices:
        - 0
    check_val_every_n_epoch: 10
    deterministic: false
    detect_anomaly: false
    precision: 16
callbacks: null
extras:
    ignore_warnings: true
    enforce_tags: false
    print_config: false
    precision:
        _target_: torch.set_float32_matmul_precision
        precision: medium
task_name: train
tags:
    - dev
ckpt_path: null
seed: 12345
test: false
paths:
    output_dir: ${model.save_dir}
