steps:
  # 0: run 20x bf -> nucseg
  #   parent: -1
  # 1: upsample nucseg to 100x
  #   parent: 0
  # 2: run NPM1 transfer function
  #   parent: -1
  # 3: run NPM1 seg
  #   parent: 2
  # 4: nucleus tracking csv
  #   parent: 1

  # step -1: delete intermediate results that aren't needed (e.g. 20x nucseg pred)


  0:
    function:
      _target_: morflowgenesis.steps.load_df.load_df
      _partial_: True
    step_type: 'string'
    parent: -1
  # 1: 
  #   function:
  #     _target_: morflowgenesis.steps.regionprops_csv.create_regionprops_csv
  #     _partial_: True
  #     save_dir: ${working_dir}/regionprops
  #     path_col: 'nuc_seg'
  #     tp_col: 'tp'
  #   step_type: 'csv'
  #   parent: 0
  1: 
    function:
      _target_: morflowgenesis.steps.build_dataset.fov_upload
      _partial_: True
      raw_cols: ['npm1_raw']
      seg_cols: ['nuc_seg', 'npm1_seg']
      tp_col: 'tp'
      output_path: ${working_dir}/fov_upload
      upload_fms: False
      dataset_name: NucleolusMorph
    step_type: 'csv'
    parent: 0
  2: 
    function:
      _target_: morflowgenesis.steps.single_cell_dataset_manifest.cell_upload2
      _partial_: True
      splitting_column: 'nuc_seg_path'
      dataset_name: NucleolusMorph
      output_path: ${working_dir}/cell_upload
      tracking_csv_path: "//allen/aics/assay-dev/users/Benji/DataForOthers/NPM1_movie/NucSeg_skoots/track/edges_100x_QC.csv"
      tp_col: 'tp'
    step_type: 'list'
    parent: 1

data: "//allen/aics/assay-dev/users/Benji/DataForOthers/NPM1_movie/npm1_seg/raw_seg_manifest.csv"
working_dir: //allen/aics/assay-dev/users/Benji/DataForOthers/NPM1_movie/NucSeg_skoots