model:
  _target_: cyto_dl.models.im2im.GAN
  save_images_every_n_epochs: 1
  save_dir: null
  x_key: lr
  compile: false
  hr_skip:
    _target_: monai.networks.blocks.Upsample
    spatial_dims: 3
    in_channels: 1
    out_channels: 16
    scale_factor:
    - 2.6134
    - 2.5005
    - 2.5005
    mode: nontrainable
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: 16
    strides:
    - 1
    - 2
    - 2
    - 2
    kernel_size:
    - 3
    - 3
    - 3
    - 3
    upsample_kernel_size:
    - 2
    - 2
    - 2
    - 2
    dropout: 0.0
    res_block: true
  task_heads:
    hr:
      _target_: cyto_dl.nn.head.gan_head_superres.GANHead_resize
      gan_loss:
        _target_: cyto_dl.nn.losses.Pix2PixHD
        scales: 1
      reconstruction_loss:
        _target_: torch.nn.MSELoss
      reconstruction_loss_weight: 1000
      save_raw: true
      in_channels: 32
      out_channels: 1
      final_act:
        _target_: torch.nn.Tanh
      resolution: hr
      upsample_ratio:
      - 2.6134
      - 2.5005
      - 2.5005
      upsample_method: nontrainable
      dense: true
      postprocess:
        input:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          dtype: numpy.float32
        prediction:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          dtype: numpy.float32
  discriminator:
    _target_: cyto_dl.nn.discriminators.MultiScaleDiscriminator
    n_scales: 1
    input_nc: 2
    n_layers: 2
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 0.0003
      weight_decay: 0.0001
      betas:
      - 0.5
      - 0.99
    discriminator:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 0.0003
      weight_decay: 0.0001
      betas:
      - 0.5
      - 0.99
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.998
    discriminator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.998
  inference_args:
    sw_batch_size: 1
    roi_size:
    - 24
    - 128
    - 128
    overlap: 0.25
    mode: gaussian
model/params/total: 8347250
model/params/trainable: 8347250
model/params/non_trainable: 0
data:
  _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
  data: null
  transforms:
  - _target_: monai.transforms.LoadImaged
    keys:
    - lr
    reader:
    - _target_: cyto_dl.image.io.MonaiBioReader
      dimension_order_out: ZYX
      C: 0
  - _target_: monai.transforms.AddChanneld
    keys:
    - lr
  - _target_: monai.transforms.ToTensord
    keys:
    - lr
  - _target_: monai.transforms.NormalizeIntensityd
    keys: lr
  num_workers: 1
  batch_size: 1
  pin_memory: true
  persistent_workers: false
trainer:
  _target_: lightning.Trainer
  default_root_dir: /allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/nucleus_transfer_function/goldilocks_replicate_no_resize_add_hr_skip/2023-09-25_14-33-39
  min_epochs: 1
  max_epochs: 1000
  accelerator: gpu
  devices:
  - 0
  check_val_every_n_epoch: 50
  deterministic: false
  detect_anomaly: false
  precision: 16
  num_sanity_val_steps: 0
callbacks: null
extras:
  ignore_warnings: true
  enforce_tags: false
  print_config: false
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
task_name: train
tags:
- dev
ckpt_path: null
seed: 12345
test: false
paths:
  output_dir: ${model.save_dir}
