experiment_name: big_lamin_seg
run_name: variance_only
task_name: train
tags:
    - dev
train: true
test: False
ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/big_lamin_seg/variance_only/2023-12-13_13-09-50/checkpoints/epoch_329.ckpt"
seed: 12345
data:
    _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
    data: null
    transforms:
        - _target_: monai.transforms.LoadImaged
          keys:
              - raw
          reader:
              # - _target_: cyto_dl.image.io.variance_reader.VarianceReader
              #   channels:
              #   - Struct
              - _target_: cyto_dl.image.io.MonaiBioReader
                dimension_order_out: "CZYX"
                C: [0]
        - _target_: cyto_dl.image.transforms.clip.Clipd
          keys: raw
        - _target_: monai.transforms.NormalizeIntensityd
          keys: raw
          channel_wise: true
    num_workers: 1
    batch_size: 1
    pin_memory: true
    persistent_workers: False
    _aux:
        patch_shape:
            - 32
            - 384
            - 384
model:
    _target_: cyto_dl.models.im2im.MultiTaskIm2Im
    compile: false
    save_images_every_n_epochs: 10
    x_key: ${source_col}
    save_dir: ${paths.output_dir}
    backbone:
        _target_: monai.networks.nets.DynUNet
        spatial_dims: 3
        in_channels: 1
        out_channels: 6
        strides:
            - 1
            - 2
            - 2
            - 2
        kernel_size:
            - 3
            - 3
            - 3
            - 3
        upsample_kernel_size:
            - 2
            - 2
            - 2
        dropout: 0.1
        res_block: true
    task_heads:
        nuc_seg:
            _target_: cyto_dl.nn.BaseHead
            save_raw: true
            loss:
                _target_: cyto_dl.models.im2im.utils.skoots.SkootsLoss
                dim: 3
                weights:
                    skeleton: 1.0
                    semantic: 40.0
                    boundary: 2.0
                    vector: 10.0
            postprocess:
                input:
                    _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
                    ch: -1
                    dtype: numpy.float32
                prediction:
                    _target_: cyto_dl.models.im2im.utils.skoots.SkootsClusterFast
                    semantic_threshold: 0

    optimizer:
        generator:
            _partial_: true
            _target_: torch.optim.AdamW
            lr: 0.0001
            weight_decay: 0.001
    lr_scheduler:
        generator:
            _partial_: true
            _target_: torch.optim.lr_scheduler.ExponentialLR
            gamma: 0.995
    inference_args:
        roi_size: ${data._aux.patch_shape}
        sw_batch_size: 1
        overlap: 0.25
        mode: gaussian
        progress: true
    _aux:
        out_channels: 32
callbacks:
trainer:
    _target_: lightning.Trainer
    default_root_dir: ${paths.output_dir}
    min_epochs: 1
    max_epochs: 1000
    accelerator: gpu
    devices:
        - 0
    check_val_every_n_epoch: 10
    deterministic: false
    detect_anomaly: false
    precision: 16
paths:
    root_dir: .
    data_dir: ${paths.root_dir}/data/
    log_dir: ${paths.root_dir}/logs/
    output_dir: ${hydra:runtime.output_dir}
    work_dir: ${hydra:runtime.cwd}
extras:
    ignore_warnings: true
    enforce_tags: false
    print_config: false
    precision:
        _target_: torch.set_float32_matmul_precision
        precision: medium
source_col: raw
target_col: nuc_seg
persist_cache: true
