working_dir: /allen/aics/assay-dev/users/Benji/hydra_workflow/mamabear_tf_and_seg

local_run: true

steps:
    - function: morflowgenesis.steps.split_image
      args:
          image_path: //allen/programs/allencell/data/proj0/935/c72/962/3cc/7a4/37b/f4f/6d8/69c/91a/71/20200323_F01_001.czi
          working_dir: ${working_dir}
          output_name: 20x_raw
          channels: [0]
          dimension_order_out: CZYX
          timepoints: -1
          scenes: ["P7-B4"]
      step_type: "init"

    # run transfer function
    - function: morflowgenesis.steps.run_cytodl
      args:
          output_name: tf
          input_step: split_image_20x_raw
          config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/local/all_nuc_tf_validation/20x_lamin_to_100x_lamin.yaml
          overrides:
              - ++ckpt_path=//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/nucleus_transfer_function/goldilocks_replicate_no_resize_add_hr_skip_large/2023-09-25_14-44-12/checkpoints/epoch_799_mod.ckpt

    # run big lamin segmentation on TF prediction
    - function: morflowgenesis.steps.run_cytodl
      args:
          output_name: big_lamin_tf
          input_step: run_cytodl_tf/hr
          config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/local/all_nuc_tf_validation/big_lamin_config.yaml

    - function: morflowgenesis.steps.tracking
      args:
          output_name: tracking
          input_step: run_cytodl_nucseg

    - function: morflowgenesis.steps.single_cell_dataset
      args:
          output_name: cells
          splitting_step: run_cytodl_nucseg
          raw_steps: [split_image_20x_raw]
          raw_steps_rename: [20x_lamin]
          seg_steps: [run_cytodl_nucseg]
          seg_steps_rename: [nuc_seg]
          tracking_step: tracking_tracking
          mask: False
          keep_lcc: False

    - function: morflowgenesis.steps.calculate_features
      args:
          output_name: features
          input_step: single_cell_dataset_cells
          features:
              - height
              - volume
              - shcoeff

    - function: morflowgenesis.steps.create_manifest
      args:
          output_name: manifest
          feature_step: calculate_features_features
          tracking_step: tracking_tracking
          single_cell_step: single_cell_dataset_cells
