working_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/validation/${deployment_name}
deployment_name: new_and_old_camera_direct_seg

local_run: True

steps:
    - function: morflowgenesis.steps.image_object_from_csv.generate_objects
      args:
          csv_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/data/20x_lamin_to_100x_seg_large/test.csv"
          working_dir: ${working_dir}
          source_column: "lr"
          non_source_columns: ["hr","nucseg"]
      step_type: "init"

    # run segmentation from 20x
    - function: morflowgenesis.steps.run_cytodl_gather.run_cytodl
      args:
          output_name: 100x_lamin_seg
          input_step: generate_objects_lr
          config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/nucleus_transfer_function_old_and_new_camera/config.yaml
      step_type: "gather"


    # create dataset with all real/tf lamin and direct/tf_watershed/lamin_watershed images
    - function: morflowgenesis.steps.single_cell_dataset.single_cell_dataset
      args:
          output_name: single_cell
          splitting_step: generate_objects_nucseg
          raw_steps: [generate_objects_hr]
          seg_steps:
              [
                  run_cytodl_100x_lamin_seg,
                  generate_objects_nucseg
              ]
          seg_steps_rename:
              [direct_seg, gt]
          keep_lcc: True
          mask: False
      step_type: "gather"

    - function: morflowgenesis.steps.feature_calculation.calculate_features
      args:
          output_name: features
          input_step: single_cell_dataset_single_cell
          features:
              - height
              - volume
              - shcoeff
      step_type: "gather"
      

    - function: morflowgenesis.steps.contact_sheet.segmentation_contact_sheet
      args:
          output_name: pred_contact_sheet
          single_cell_dataset_step: single_cell_dataset_single_cell
          feature_step: calculate_features_features
          raw_name: generate_objects_hr
          segmentation_name: gt
          x_feature: volume
          y_feature: height
          seg_names: [gt, direct_seg]
      step_type: "gather"

    - function: morflowgenesis.steps.pca.run_pca
      args:
          output_name: pca
          feature_step: calculate_features_features
          features_regex: ".*shcoeffs.*"
          calculate_name: gt
          apply_names: [gt, direct_seg]
      step_type: "gather"

    - function: morflowgenesis.steps.plot.run_plot
      args:
          output_name: plot
          input_step: calculate_features_features
          features: [volume, height]
          label:
              segmentation_name: gt
              description: "Watershed on Real Lamin"
          pred:
              - segmentation_name: direct_seg
                description: End to End Segmentation
      step_type: "gather"

    - function: morflowgenesis.steps.plot.run_plot
      args:
          output_name: pca_plot
          input_step: run_pca_pca
          features: [PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10]
          label:
              segmentation_name: gt
              description: "Watershed on Real Lamin"
          pred:
              - segmentation_name: direct_seg
                description: End to End Segmentation
      step_type: "gather"
