experiment_name: nuc_and_cellseg_20x
run_name: skoots
task_name: train
tags:
    - dev
train: true
test: false
ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/nuc_and_cellseg_20x/skoots/2023-06-16_11-26-12/checkpoints/last.ckpt"
seed: 12345
data:
    _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
    data:
    transforms:
        _target_: monai.transforms.Compose
        transforms:
            - _target_: monai.transforms.LoadImaged
              keys: ${source_col}
              reader:
                  - _target_: cyto_dl.image.io.MonaiBioReader
                    dimension_order_out: "ZYX"
                    C: 1
            - _target_: monai.transforms.AddChanneld
              keys: ${source_col}
            - _target_: monai.transforms.ToTensord
              keys: ${source_col}
            - _target_: monai.transforms.NormalizeIntensityd
              keys: ${source_col}

    num_workers: 0
    batch_size: 1
    pin_memory: True
    persistent_workers: False
    _aux:
        patch_shape: [32, 128, 128]

model:
    _target_: cyto_dl.models.im2im.MultiTaskIm2Im
    save_images_every_n_epochs: 1
    x_key: ${source_col}
    inference_heads: [nucseg]
    compile: True
    save_dir:
    backbone:
        _target_: monai.networks.nets.DynUNet
        spatial_dims: 3
        in_channels: 1
        out_channels: 128
        strides:
            - 1
            - 2
            - 2
            - 2
        kernel_size:
            - 3
            - 3
            - 3
            - 3
        upsample_kernel_size:
            - 2
            - 2
            - 2
        dropout: 0.0
        res_block: true
    task_heads:
        caaxseg:
            _target_: cyto_dl.nn.ResBlocksHead
            in_channels: 128
            out_channels: 6
            n_convs: 3
            loss:
                _target_: cyto_dl.models.im2im.utils.skoots.SkootsLoss
                dim: 3
            save_raw: true
            dense: true
            postprocess:
                prediction:
                    _target_: cyto_dl.models.im2im.utils.skoots.SkootsCluster
                    skel_threshold: -1.5
                    semantic_threshold: -7
                    distance_threshold: 8
                    min_size: 0
        nucseg:
            _target_: cyto_dl.nn.ResBlocksHead
            in_channels: 128
            out_channels: 6
            n_convs: 3
            loss:
                _target_: cyto_dl.models.im2im.utils.skoots.SkootsLoss
                dim: 3
            save_raw: true
            dense: true
            postprocess:
                prediction:
                    _target_: cyto_dl.models.im2im.utils.skoots.SkootsCluster
                    skel_threshold: -4
                    semantic_threshold: -7
                    distance_threshold: 8
                    min_size: 0

    optimizer:
        generator:
            _partial_: true
            _target_: torch.optim.AdamW
            lr: 0.0005
            weight_decay: 0.0001
    lr_scheduler:
        generator:
            _partial_: true
            _target_: torch.optim.lr_scheduler.CosineAnnealingLR
            T_max: ${trainer.max_epochs}
            eta_min: 1.0e-06
    inference_args:
        roi_size: ${data._aux.patch_shape}
        sw_batch_size: 1
        mode: gaussian
        overlap: 0.25
callbacks:
logger:
trainer:
    _target_: lightning.pytorch.Trainer
    default_root_dir: ${paths.output_dir}
    min_epochs: 1
    max_epochs: 1000
    accelerator: gpu
    devices: 1
    check_val_every_n_epoch: 10
    deterministic: false
    detect_anomaly: false
    precision: 16
    num_sanity_val_steps: 1
    gradient_clip_val: 0.8
    accumulate_grad_batches: 2
paths:
    root_dir: .
    data_dir: ${paths.root_dir}/data/
    log_dir: ${paths.root_dir}/logs/
    output_dir: . #${hydra:runtime.output_dir}
    work_dir: . #${hydra:runtime.cwd}
extras:
    ignore_warnings: true
    enforce_tags: False
    print_config: true
    precision:
        _target_: torch.set_float32_matmul_precision
        precision: medium
source_col: raw
target_col1: nucseg
target_col2: caaxseg
persist_cache: true
