experiment_name: pretrain_comp
run_name: finetune_GAN_dilate_best_dataset
task_name: train
tags:
- dev
train: true
test: false
ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/pretrain_comp/finetune_GAN_dilate_best_dataset/2023-12-13_14-09-15/checkpoints/epoch_189.ckpt"
seed: 12345
data:
    _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
    data: null
    transforms:
      - _target_: monai.transforms.LoadImaged
        keys:
        - ${source_col}
        reader:
        - _target_: cyto_dl.image.io.MonaiBioReader
          dimension_order_out: CZYX
          C: 0
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ${source_col}
      - _target_: monai.transforms.ToTensord
        keys:
        - ${source_col}
        dtype: float16
      - _target_: monai.transforms.CenterSpatialCropd
        keys: raw
        roi_size: [24, -1, -1]
    _aux:
        patch_shape:
            - 24
            - 128
            - 128
    num_workers: 1
    batch_size: 1
    pin_memory: true
    persistent_workers: false
model:
  _target_: cyto_dl.models.im2im.MultiTaskIm2Im
  compile: false
  save_images_every_n_epochs: 1
  x_key: ${source_col}
  save_dir: ${paths.output_dir}
  hr_skip:
    _target_: monai.networks.blocks.Upsample
    spatial_dims: 3
    in_channels: 1
    out_channels: 32
    scale_factor:
    - 2.6134
    - 2.5005
    - 2.5005
    mode: nontrainable
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: 32
    strides:
    - 1
    - 2
    - 1
    - 2
    - 1
    - 2
    kernel_size:
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    upsample_kernel_size:
    - 2
    - 1
    - 2
    - 1
    - 2
    dropout: 0.0
    res_block: true
    filters:
    - 96
    - 192
    - 288
    - 384
    - 480
    - 576
  task_heads:
    nucseg:
      _target_: cyto_dl.nn.ResBlocksHead
      in_channels: 64
      out_channels: 6
      resolution: hr
      dense: true
      n_convs: 3
      upsample_method: nontrainable
      upsample_ratio:
      - 2.6134
      - 2.5005
      - 2.5005
      loss:
        _target_: cyto_dl.models.im2im.utils.skoots.SkootsLoss
        dim: 3
        weights:
          skeleton: 1.0
          semantic: 10.0
          boundary: 1.0
          vector: 5.0
      postprocess:
        input:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          ch: -1
          dtype: numpy.float32
        prediction:
          _target_: cyto_dl.models.im2im.utils.skoots.SkootsClusterFast
          skel_threshold: -3
          semantic_threshold: -2
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.AdamW
      lr: 0.0001
      weight_decay: 0.001
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.995
  inference_args:
    roi_size: ${data._aux.patch_shape}
    sw_batch_size: 1
    overlap: 0.25
    mode: gaussian
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 300
  accelerator: gpu
  devices:
  - 0
  check_val_every_n_epoch: 10
  deterministic: false
  detect_anomaly: false
  precision: 16
paths:
  root_dir: .
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: true
  enforce_tags: False
  print_config: False
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
source_col: raw
target_col: nucseg
persist_cache: true
