experiment_name: breakdown_classification
run_name: add_shift_aug
task_name: train
tags:
    - dev
train: true
test: false
ckpt_path: null
seed: 12345
data:
    _target_: cyto_dl.datamodules.dataframe.DataframeDatamodule
    path: //allen/aics/assay-dev/users/Benji/CurrentProjects/breakdown_classifier_cyto_dl/data/precalculated_movies
    cache_dir: null
    num_workers: 1
    batch_size: 1
    pin_memory: true
    transforms:
        train:
            _target_: monai.transforms.Compose
            transforms:
                - _target_: monai.transforms.LoadImaged
                  keys: img
                  reader:
                      - _target_: cyto_dl.image.io.MonaiBioReader
                        dimension_order_out: ZYX
                - _target_: cyto_dl.image.transforms.track_transforms.GenerateTrackLabels
                - _target_: cyto_dl.image.transforms.track_transforms.TrackCrop
                - _target_: monai.transforms.ToTensord
                  keys: img
                  dtype: float16
                - _target_: cyto_dl.image.transforms.track_transforms.PerChannel
                  keys:
                      - img
                  transform:
                      _target_: monai.transforms.RandShiftIntensity
                      offsets: 3
                      prob: 0.5
                - _target_: cyto_dl.image.transforms.track_transforms.PerChannel
                  keys:
                      - img
                  transform:
                      _target_: monai.transforms.RandScaleIntensity
                      factors: 0.5
                      prob: 0.5
                - _target_: monai.transforms.RandFlipd
                  keys: img
                  prob: 0.5
                  spatial_axis: 0
                - _target_: monai.transforms.RandFlipd
                  keys: img
                  prob: 0.5
                  spatial_axis: 1
                - _target_: monai.transforms.RandRotate90d
                  keys: img
                  prob: 0.75
                - _target_: cyto_dl.image.transforms.track_transforms.PerChannel
                  keys:
                      - img
                  transform:
                      _target_: monai.transforms.RandAdjustContrast
                      gamma:
                          - 0.8
                          - 1.2
                      prob: 0.5
                - _target_: cyto_dl.image.transforms.track_transforms.CropResize
                  keys:
                      - img
        val:
            _target_: monai.transforms.Compose
            transforms:
                - _target_: monai.transforms.LoadImaged
                  keys: img
                  reader:
                      - _target_: cyto_dl.image.io.MonaiBioReader
                        dimension_order_out: ZYX
                - _target_: cyto_dl.image.transforms.track_transforms.GenerateTrackLabels
                - _target_: monai.transforms.ToTensord
                  keys: img
                  dtype: float16
        test:
            _target_: monai.transforms.Compose
            transforms:
                - _target_: monai.transforms.LoadImaged
                  keys: img
                  reader:
                      - _target_: cyto_dl.image.io.MonaiBioReader
                        dimension_order_out: ZYX
                - _target_: cyto_dl.image.transforms.track_transforms.GenerateTrackLabels
                - _target_: monai.transforms.ToTensord
                  keys: img
                  dtype: float16
        predict:
            _target_: monai.transforms.Compose
            transforms:
                - _target_: monai.transforms.LoadImaged
                  keys: img
                  reader:
                      - _target_: cyto_dl.image.io.MonaiBioReader
                        dimension_order_out: ZYX
                - _target_: monai.transforms.ToTensord
                  keys: img
                  dtype: float16
model:
    _target_: cyto_dl.models.classification_transformer.Classifier
    num_classes: ${model._aux.num_classes}
    model:
        _target_: cyto_dl.nn.track_sequence_predictor.TrackClassifier
        patch_size:
            - 1
            - 64
            - 64
        pos_embedding_length: 150
        num_classes: ${model._aux.num_classes}
    x_key: img
    save_dir: ${paths.output_dir}
    save_images_every_n_epochs: 1
    optimizer:
        _partial_: true
        _target_: torch.optim.AdamW
        weight_decay: 0.01
    lr_scheduler:
        _partial_: true
        _target_: torch.optim.lr_scheduler.OneCycleLR
        max_lr: 0.0003
        epochs: ${trainer.max_epochs}
        steps_per_epoch: 1
        pct_start: 0.1
    _aux:
        num_classes: 2
trainer:
    _target_: lightning.Trainer
    default_root_dir: ${paths.output_dir}
    min_epochs: 1
    max_epochs: 130
    accelerator: gpu
    devices: 1
    precision: 16
    check_val_every_n_epoch: 10
    deterministic: false
    detect_anomaly: false
    gradient_clip_val: 10.0
paths:
    root_dir: .
    data_dir: ${paths.root_dir}/data/
    log_dir: ${paths.root_dir}/logs/
    output_dir: ${hydra:runtime.output_dir}
    work_dir: ${hydra:runtime.cwd}
extras:
    ignore_warnings: true
    enforce_tags: false
    print_config: false
    precision:
        _target_: torch.set_float32_matmul_precision
        precision: medium
persist_cache: false
