working_dir: /allen/aics/assay-dev/users/Benji/hydra_workflow/mamabear_pretrain

local_run: true

steps:
    # - function: morflowgenesis.steps.generate_objects
    #   args:
    #       csv_path: "//allen/aics/assay-dev/users/Benji/hydra_workflow/mamabear_pretrain/manifest.csv"
    #       working_dir: ${working_dir}
    #       source_column: lr
    #       non_source_columns: [
    #         nucseg
    #       ]
    #       metadata_column: metadata
    #   step_type: "init"

    # - function: morflowgenesis.steps.tracking
    #   args:
    #       output_name: tracking
    #       input_step: generate_objects_nucseg

    # - function: morflowgenesis.steps.single_cell_dataset
    #   args:
    #       output_name: cells
    #       splitting_step: generate_objects_nucseg
    #       raw_steps: [generate_objects_lr]
    #       raw_steps_rename: [20x_lamin]
    #       seg_steps: [generate_objects_nucseg]
    #       seg_steps_rename: [nuc_seg]
    #       tracking_step: tracking_tracking
    #       mask: False
    #       keep_lcc: False

    - function: morflowgenesis.steps.calculate_features
      args:
          output_name: features
          input_step: single_cell_dataset_cells
          features:
              - height
              - volume
              - shcoeff

    - function: morflowgenesis.steps.create_manifest
      args:
          output_name: manifest
          feature_step: calculate_features_features
          single_cell_step: single_cell_dataset_cells
