defaults:
    - split_image@steps: ../../steps/split_image
    - center_crop@steps: ../../steps/center_crop
    - run_cytodl@steps: ../../steps/run_cytodl
    - center_pad@steps: ../../steps/center_pad
    - tracking@steps: ../../steps/tracking
    - single_cell_dataset@steps: ../../steps/single_cell_dataset
    - create_manifest@steps: ../../steps/create_manifest
    - consistency_validation@steps: ../../steps/consistency_validation

# here we can create workflow-level arguments
working_dir: /allen/aics/assay-dev/users/Benji/hydra_workflow/fixed_validation_crossmae_multich/

steps:
    split_image:
        image_path: //allen/programs/allencell/data/proj0/029/bca/2b7/002/559/9ea/94e/29a/501/25f/c0/20220901_AD00001016_20X_L01_001_020.tif
        channels: [1]
        working_dir: ${workflow.working_dir}
        timepoints: -1
        dimension_order_out: CZYX

    center_crop:
        image_step: split_image/split_image

    run_cytodl:
        input_step: center_crop/center_crop
        config_path: ${paths.model_dir}/vit_new.yaml
        overrides:
            ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/flexi_mae/multich_proj_decoder_cross_mae/2024-03-05_12-23-49/checkpoints/epoch_269.ckpt"
            semantic_thresh: 6

    center_pad:
        image_step: run_cytodl/nucseg
        cropping_step: center_crop/center_crop
        pad_rescale: 2.6134

    tracking:
        input_step: center_pad/center_pad

    single_cell_dataset:
        splitting_step: nuc_seg
        seg_steps: [center_pad/center_pad]
        seg_steps_rename: [nuc_seg]
        mask: False
        keep_lcc: False
        input_res: [0.29, 0.108, 0.108]
        out_res: 0.108
        padding: [10, 25, 25]
        features:
            - _target_: morflowgenesis.features.Volume
            - _target_: morflowgenesis.features.Height
            - _target_: morflowgenesis.features.HeightPercentile
            - _target_: morflowgenesis.features.AxisLengths
        save: False

    create_manifest:
        breakdown_classification_step: null
        dataset_name: fixed_test
