working_dir: /allen/aics/assay-dev/users/Benji/DataForOthers/NPM1_movie/workflow_version/

steps:
  0:
    function:
      _target_: morflowgenesis.steps.split_czi.split_czi
      _partial_: True
      czi_path:  /allen/aics/assay-dev/MicroscopyData/Frick/2023/20230327/ZSD0/AICS86_day3_nucleolus_movie_interactive-01-1.czi/AICS86_day3_nucleolus_movie_interactive-01-1_AcquisitionBlock1.czi/AICS86_day3_nucleolus_movie_interactive-01-1_AcquisitionBlock1_pt1.czi
      # NPM1, bf, FBL
      step_name: split_czi
      working_dir: ${working_dir}
      output_name: 20x_raw
      channels: -1
      dimension_order_out: CZYX
      timepoints: [0,1,2,3]
      scenes: [P4-F6]
    step_type: 'none'
  1:
    function:
      _target_: morflowgenesis.steps.run_cytodl.run_cytodl
      _partial_: True
      step_name: run_cytodl
      output_name: 20x_nucseg
      input_step: split_czi_20x_raw
      config_path: .configs/step/20x_bf_to_20x_nucseg.yaml
    step_type: 'list'
  2:
    function:
      _target_: morflowgenesis.steps.resize_image.run_resize
      _partial_: True
      step_name: resize
      output_name: 100x_nucseg
      input_step: run_cytodl_20x_nucseg
      output_shape: [120,  3120, 4620]
    step_type: 'list'
  3:
    function:
      _target_: morflowgenesis.steps.run_cytodl.run_cytodl
      _partial_: True
      step_name: run_cytodl
      output_name: 100x_npm1
      input_step: split_czi_20x_raw
      config_path: .configs/step/20x_npm1_to_100x_npm1.yaml
    step_type: 'list'
  4:
    function:
      _target_: morflowgenesis.steps.run_cytodl.run_cytodl
      _partial_: True
      step_name: run_cytodl
      output_name: 100x_npm1_seg
      input_step: run_cytodl_100x_npm1
      config_path: .configs/step/100x_npm1_to_100x_npm1_seg.yaml
    step_type: 'list'
  5: 
    function:
      _target_: morflowgenesis.steps.tracking.run_tracking
      _partial_: True
      step_name: run_tracking
      output_name: tracking
      input_step: resize_100x_nucseg
    step_type: 'gather'
  6: 
    function:
      _target_: morflowgenesis.steps.single_cell_dataset.single_cell_dataset
      _partial_: True
      step_name: single_cell_dataset
      output_name: single_cell_dataset
      splitting_step: resize_100x_nucseg
      raw_steps: [run_cytodl_100x_npm1]
      seg_steps: [run_cytodl_100x_npm1_seg, resize_100x_nucseg] 
      tracking_step: run_tracking_tracking
    step_type: 'list'

  # step -1: delete intermediate results that aren't needed (e.g. 20x nucseg pred)

