# tagging with @steps adds the default under the steps key
# the order of import determines the order of execution
# note that currently we can't run the same step multiple times with different arguments
defaults:
    - split_image@steps: ../../steps/split_image
    - center_crop@steps: ../../steps/center_crop
    - run_cytodl@steps: ../../steps/run_cytodl
    - center_pad@steps: ../../steps/center_pad
    - tracking@steps: ../../steps/tracking
    - single_cell_dataset@steps: ../../steps/single_cell_dataset
    - formation_breakdown@steps: ../../steps/formation_breakdown
    - create_manifest@steps: ../../steps/create_manifest

# here we can create workflow-level arguments
working_dir: /allen/aics/assay-dev/users/Benji/hydra_workflow/drug_perturbation_4_to_86/${workflow.scene}

image_path:
timepoint_end:
name:
channels: [0]
scene:

# here we can override arguments for specific steps, but changing the order here does not change the order of execution
# task runner args can be overridden, but the TYPE of task runner cannot be changed from the workflow. To use the PACKAGE default task runner of concurrent task runner, set task_runner: null
steps:
    split_image:
        image_path: ${workflow.image_path}
        channels: ${workflow.channels}
        working_dir: ${workflow.working_dir}
        timepoint_end: ${workflow.timepoint_end}
        scenes:
            - ${workflow.scene}

    center_crop:
        image_step: split_image/split_image

    run_cytodl:
        input_step: center_crop/center_crop
        config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/model/vit_config.yaml
        overrides:
            ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/flexi_mae/offset_aug_finetune_aligned_large/2024-01-28_19-42-12/checkpoints/last.ckpt"

    center_pad:
        image_step: run_cytodl/nucseg
        cropping_step: center_crop/center_crop
        pad_rescale: 2.6134

    tracking:
        input_step: center_pad/center_pad

    single_cell_dataset:
        splitting_step: center_pad/center_pad
        raw_steps: [split_image/split_image]
        raw_steps_rename: [20x_lamin]
        seg_steps: [center_pad/center_pad]
        seg_steps_rename: [nuc_seg]
        mask: False
        keep_lcc: False
        input_res:
            nuc_seg: [0.29, 0.108, 0.108]
            20x_lamin: [0.738, 0.27, 0.27]
        out_res:
            nuc_seg: 0.108
            20x_lamin: 0.108
        padding: [10, 25, 25]
        features:
            nuc_seg:
                - _target_: morflowgenesis.features.Volume
                - _target_: morflowgenesis.features.SurfaceArea
                - _target_: morflowgenesis.features.Height
                - _target_: morflowgenesis.features.HeightPercentile
                - _target_: morflowgenesis.features.SHCoeff
                - _target_: morflowgenesis.features.AxisLengths

    formation_breakdown:
        image_step: split_image/split_image
        config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/model/breakdown_per_tp.yaml
        overrides:
            ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/breakdown_classification/single_timepoint/2024-02-05_13-00-47/checkpoints/epoch_109.ckpt"
        min_track_length: 2

    create_manifest:
        dataset_name: ${workflow.name}
    # steps not in the overrides can also be added here. they must be in order and must have all required arguments since they are not overriding args
