defaults:
    - generate_objects@steps: ../../steps/generate_objects
    - run_cytodl@steps: ../../steps/run_cytodl
    - threshold@steps: ../../steps/threshold
    - align_segmentations_to_image@steps: ../../steps/align_segmentations_to_image
    - run_watershed@steps: ../../steps/run_watershed
    - single_cell_dataset@steps: ../../steps/single_cell_dataset
    - plot@steps: ../../steps/plot

# here we can create workflow-level arguments
working_dir: /allen/aics/assay-dev/users/Benji/hydra_workflow/shape_opt_vit_new

steps:
    generate_objects:
        csv_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/aics-im2im/logs/train/runs/flexi_mae/conv_only_decoder/2024-01-17_19-59-02/predict_images/manifest.csv"
        working_dir: ${workflow.working_dir}
        source_column: lr
        non_source_columns: [hr]

    run_cytodl:
        input_step: generate_objects/lr
        config_path: ${paths.model_dir}vit_new.yaml
        overrides:
            ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/flexi_mae/multich_proj_decoder_cross_mae/2024-03-05_12-23-49/checkpoints/epoch_269.ckpt"

    threshold:
        output_name: thresh
        input_step: run_cytodl/nucseg
        start: -4
        stop: 4
        step: 1
        label: True

    align_segmentations_to_image:
        image_step: generate_objects/hr
        segmentation_steps: [threshold/thresh/0.0]

    run_watershed:
        output_name: real_lamin
        raw_input_step: generate_objects/hr
        seg_input_step: threshold/thresh/0.0
        mode: "erosion"
        erosion: 5
        include_edge: False

    single_cell_dataset:
        splitting_step: run_watershed/real_lamin
        seg_steps: [threshold/thresh.*, run_watershed/real_lamin]
        mask: False
        keep_lcc: True
        input_res: [0.29, 0.108, 0.108]
        out_res: 0.108
        padding: [10, 25, 25]
        features:
            - _target_: morflowgenesis.features.Volume
            - _target_: morflowgenesis.features.HeightPercentile
        save: False

    plot:
        features: [volume, height_percentile]
        label:
            segmentation_name: run_watershed/real_lamin
            description: "Watershed on Real Lamin"
        pred:
            - segmentation_name: threshold/thresh/.*
              description: End to End Segmentation
