working_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/validation/cytodata/${deployment_name}
deployment_name: bf_to_nucseg

local_run: True

steps:
    # get paired bf / TF-predicted 100x Lamin
    # - function: morflowgenesis.steps.image_object_from_csv.generate_objects
    #   args:
    #     csv_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/data/paired_dataset_tf_lf/lf/lf_to_100x_lamin_manifests/test.csv"
    #     working_dir: ${working_dir}
    #     source_column: bf
    #     non_source_columns: [lamin]
    #   step_type: "init"

    # # predict nucseg from 20x brightfield
    # - function: morflowgenesis.steps.run_cytodl_gather.run_cytodl
    #   args:
    #     output_name: pred_nucseg
    #     input_step: generate_objects_bf
    #     config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/cellnucmorph_cytodata/bf_to_lamin_validation/model.yaml
    #   step_type: "gather"

    # # watershed on hr pred lamin
    # - function: morflowgenesis.steps.segmentation_seeded_watershed.run_watershed
    #   args:
    #     output_name: nucseg
    #     raw_input_step: generate_objects_lamin
    #     seg_input_step: run_cytodl_pred_nucseg
    #     mode: 'erosion'
    #     erosion: 5
    #     include_edge: False

    # # create dataset with pred 100x lamin, "gt"100x lamin, and nucseg
    # - function: morflowgenesis.steps.single_cell_dataset.single_cell_dataset
    #   args:
    #     output_name: single_cell
    #     splitting_step: run_watershed_nucseg
    #     raw_steps: [generate_objects_lamin]
    #     seg_steps: [run_watershed_nucseg, run_cytodl_pred_nucseg]
    #     seg_steps_rename: [gt_nucseg, nucseg_from_bf]
    #     keep_lcc: True
    #     mask: False
    #     iou_thresh: 0.7
    #     include_edge_cells: False

    - function: morflowgenesis.steps.feature_calculation.calculate_features
      args:
        output_name: features
        input_step: single_cell_dataset_single_cell
        reference_channel: gt_nucseg
        features:
            - height
            - volume
            - shcoeff

    # - function: morflowgenesis.steps.contact_sheet.segmentation_contact_sheet
    #   args:
    #     output_name: pred_contact_sheet
    #     single_cell_dataset_step: single_cell_dataset_single_cell
    #     feature_step: calculate_features_features
    #     raw_name: generate_objects_lamin
    #     segmentation_name: gt_nucseg
    #     x_feature: volume
    #     y_feature: height
    #     seg_names: [gt_nucseg, nucseg_from_bf]
    #   step_type: 'gather'

    - function: morflowgenesis.steps.pca.run_pca
      args:
        output_name: pca
        feature_step: calculate_features_features
        features_regex: '.*shcoeffs.*'
        calculate_name: gt_nucseg
        apply_names: [nucseg_from_bf]
      step_type: 'gather'
        
    - function: morflowgenesis.steps.plot.run_plot
      args:
        output_name: plot
        input_step: calculate_features_features
        features: [volume, height]
        label:
          segmentation_name: gt_nucseg
          description: 'Watershed on psuedo-GT Lamin'
        pred:
          - segmentation_name: nucseg_from_bf
            description: Watershed on Lamin from BF
      step_type: 'gather'

    - function: morflowgenesis.steps.plot.run_plot
      args:
        output_name: pca_plot
        input_step: run_pca_pca
        features: [PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10]
        label:
          segmentation_name: gt_nucseg
          description: 'Watershed on psuedo-GT Lamin'
        pred:
          - segmentation_name: nucseg_from_bf
            description: Watershed on Lamin from BF
      step_type: 'gather'
