working_dir: /allen/aics/assay-dev/users/Benji/CurrentProjects/cytodata/${deployment_name}
deployment_name: project

local_run: True

steps:
    - function: morflowgenesis.steps.image_object_from_csv.generate_objects
      args:
        csv_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/cellnucmorph_cytodata/manifest.csv
        working_dir: ${working_dir}
        source_column: "Brightfield"
        non_source_columns: ["CAAX"]
      step_type: "init"

    # # 20x caax -> 100x CAAX
    # - function: morflowgenesis.steps.run_cytodl_gather.run_cytodl
    #   args:
    #     output_name: 100x_CAAX
    #     input_step: generate_objects_CAAX
    #     config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/cellnucmorph_cytodata/caax_tf_validation/model.yaml
    #   step_type: "gather"

    # #100x Caax -> 100x Cellseg
    # - function: morflowgenesis.steps.run_cytodl_gather.run_cytodl
    #   args:
    #     output_name: 100x_cellseg
    #     input_step: run_cytodl_100x_CAAX
    #     config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/cellnucmorph_cytodata/caax_iseg_validation/model.yaml
    #   step_type: "gather"

    # # 20x BF -> 100x iseg
    # - function: morflowgenesis.steps.run_cytodl_gather.run_cytodl
    #   args:
    #     output_name: 100x_lamin
    #     input_step: generate_objects_Brightfield
    #     config_path: 
    #   step_type: "gather"

    # # generate meshes
    # - function: morflowgenesis.steps.segmentation_mesh.create_mesh
    #   args:
    #     output_name: mesh
    #     segmentation_steps: [run_cytodl_100x_cellseg, run_cytodl_100x_nucseg]
    #     resize: [0.53, 0.2, 0.2]

    # max and side project all
    - function: morflowgenesis.steps.project.project
      args:
        output_name: project
        input_steps: [generate_objects_Brightfield, generate_objects_CAAX]
        project_type: slice
        project_slice: 15

    - function: morflowgenesis.steps.project.project
      args:
        output_name: project
        input_steps: [generate_objects_Brightfield, generate_objects_CAAX]
        project_type: slice
        project_slice: 600
        axis: 1
        scale: [0.38, 0.2, 0.2]

    # - function: morflowgenesis.steps.project.project
    #   args:
    #     output_name: project
    #     input_steps: [run_cytodl_100x_CAAX, run_cytodl_100x_lamin, run_cytodl_100x_nucseg, run_cytodl_100x_cellseg]
    #     project_type: slice
    #     project_slice: 41

    # - function: morflowgenesis.steps.project.project
    #   args:
    #     output_name: project
    #     input_steps: [run_cytodl_100x_CAAX, run_cytodl_100x_lamin, run_cytodl_100x_nucseg, run_cytodl_100x_cellseg]
    #     project_type: slice
    #     project_slice: 1500
    #     axis: 1
    #     scale: [0.537, 0.2, 0.2]

    # - function: morflowgenesis.steps.tracking.run_tracking
    #   args:
    #       working_dir: ${working_dir}
    #       output_name: tracking
    #       input_step: run_cytodl_100x_lamin
    #   step_type: "gather"

    # - function: morflowgenesis.steps.single_cell_dataset.single_cell_dataset
    #   args:
    #       output_name: cells
    #       splitting_step: run_resize_100x_cellseg
    #       raw_steps: [run_cytodl_100x_CAAX, run_cytodl_100x_lamin]
    #       seg_steps: [run_cytodl_100x_cellseg, run_resize_100x_nucseg]
    #       seg_steps_rename: [cellseg, nucseg]
    #       tracking_step: run_tracking_tracking
    #       mask: False

    # - function: morflowgenesis.steps.feature_calculation.calculate_features
    #   args:
    #     output_name: features
    #     input_step: single_cell_dataset_cells
    #     segmentation_columns: [crop_seg_path]
    #     features:
    #         - height
    #         - volume
    #         - shcoeff

    # # generate shape space
    # - function: morflowgenesis.steps.generate_shape_space.make_shape_space
    #   args:
    #     output_name: shape_space
    #     feature_step: calculate_features_features
    #     segmentation_names: [cellseg, 'nucseg']
    #   step_type: 'gather'

