task_limit: 50
memory_limit: 5Gi
processes: False

_target_: prefect_dask.DaskTaskRunner
cluster_class: distributed.LocalCluster
cluster_kwargs:
    n_workers: ${..task_limit}
    memory_limit: ${..memory_limit}
    processes: ${..processes}
    threads_per_worker: 1
    resources:
        cpu: 2
