working_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/validation/cytodata/${deployment_name}
deployment_name: nucleus_transfer_function2

local_run: True

steps:
    - function: morflowgenesis.steps.image_object_from_csv.generate_objects
      args:
        csv_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/cellnucmorph_cytodata/lamin_tf_validation/manifest.csv
        working_dir: ${working_dir}
        source_column: "lr"
        non_source_columns: ["hr", "seg"]
      step_type: "init"

    # run transfer function
    - function: morflowgenesis.steps.run_cytodl_gather.run_cytodl
      args:
        output_name: tf_lamin
        input_step: generate_objects_lr
        config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/cellnucmorph_cytodata/lamin_tf_validation/model.yaml
      step_type: "gather"

    # watershed on tf lamin 
    - function: morflowgenesis.steps.segmentation_seeded_watershed.run_watershed
      args:
        output_name: tf_lamin
        raw_input_step: run_cytodl_tf_lamin
        seg_input_step: generate_objects_seg
        mode: 'erosion'
        include_edge: False
        erosion: 5

    # create dataset with all real/tf lamin and direct/tf_watershed/lamin_watershed images
    - function: morflowgenesis.steps.single_cell_dataset.single_cell_dataset
      args:
        output_name: single_cell
        splitting_step: run_watershed_tf_lamin
        raw_steps: [generate_objects_hr, run_cytodl_tf_lamin]
        seg_steps: [generate_objects_seg, run_watershed_tf_lamin]
        seg_steps_rename: [real_seg, tf_seg]
        keep_lcc: True
        mask: False

    - function: morflowgenesis.steps.feature_calculation.calculate_features
      args:
        output_name: features
        input_step: single_cell_dataset_single_cell
        features:
            - height
            - volume
            - shcoeff

    - function: morflowgenesis.steps.contact_sheet.segmentation_contact_sheet
      args:
        output_name: pred_contact_sheet
        single_cell_dataset_step: single_cell_dataset_single_cell
        feature_step: calculate_features_features
        raw_name: generate_objects_hr
        segmentation_name: real_seg
        x_feature: volume
        y_feature: height
        seg_names: [tf_seg, real_seg]
      step_type: 'gather'

    - function: morflowgenesis.steps.pca.run_pca
      args:
        output_name: pca
        feature_step: calculate_features_features
        features_regex: '.*shcoeffs.*'
        calculate_name: real_seg
        apply_names: [tf_seg]
      step_type: 'gather'
        

    - function: morflowgenesis.steps.plot.run_plot
      args:
        output_name: plot
        input_step: calculate_features_features
        features: [volume, height]
        label:
          segmentation_name: real_seg
          description: 'Watershed on Real Lamin'
        pred:
          - segmentation_name: tf_seg
            description: Watershed on TF Lamin
      step_type: 'gather'

    - function: morflowgenesis.steps.plot.run_plot
      args:
        output_name: pca_plot
        input_step: run_pca_pca
        features: [PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10]
        label:
          segmentation_name: real_seg
          description: 'Watershed on Real Lamin'
        pred:
          - segmentation_name: tf_seg
            description: Watershed on TF Lamin
      step_type: 'gather'
