experiment_name: cytodata_models
run_name: caax_tf
task_name: train
tags:
- dev
train: true
test: false
ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/cytodata_models/caax_tf/2023-10-04_16-09-10/checkpoints/epoch_999_mod.ckpt"
seed: 12345
data:
  _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
  data: 
    - lr: //allen/aics/assay-dev/users/Benji/CurrentProjects/20xBF_to_cellseg/CELLMORPH/cellmorph_run_scene_3/step_prep/20200622_N02_001-Scene-03-P4-B2_S0/CAAX/img_T0.tiff
  transforms:
  - _target_: monai.transforms.LoadImaged
    keys: ${source_col}
    reader:
    - _target_: cyto_dl.image.io.MonaiBioReader
      dimension_order_out: ZYX
      C: ${channel}
  - _target_: monai.transforms.AddChanneld
    keys: ${source_col}
  - _target_: monai.transforms.ToTensord
    keys: ${source_col}
  - _target_: monai.transforms.NormalizeIntensityd
    keys: ${source_col}
  - _target_: cyto_dl.image.transforms.clip.Clipd
    keys: ${source_col}
    low: -7
    high: 13 
    percentile: False
  _aux:
    patch_shape:
    - 24
    - 128
    - 128
  num_workers: 1
  batch_size: 1
  pin_memory: true
  persistent_workers: false
model:
  _target_: cyto_dl.models.im2im.GAN
  save_images_every_n_epochs: 1
  save_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/validation/cytodata/skoots_test
  x_key: ${source_col}
  compile: false
  hr_skip:
    _target_: monai.networks.blocks.Upsample
    spatial_dims: 3
    in_channels: 1
    out_channels: 16
    scale_factor:
    - 2.6134
    - 2.5005
    - 2.5005
    mode: nontrainable
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: 16
    strides:
    - 1
    - 2
    - 2
    - 2
    kernel_size:
    - 3
    - 3
    - 3
    - 3
    upsample_kernel_size:
    - 2
    - 2
    - 2
    - 2
    dropout: 0.0
    res_block: true
  task_heads:
    hr:
      _target_: cyto_dl.nn.head.gan_head_superres.GANHead_resize
      gan_loss:
        _target_: cyto_dl.nn.losses.Pix2PixHD
        scales: ${model.discriminator.n_scales}
      reconstruction_loss:
        _target_: torch.nn.MSELoss
      reconstruction_loss_weight: 1000
      save_raw: true
      in_channels: 32
      out_channels: 1
      final_act:
        _target_: torch.nn.Tanh
      resolution: hr
      upsample_ratio:
      - 2.6134
      - 2.5005
      - 2.5005
      upsample_method: nontrainable
      dense: true
      postprocess:
        input:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          dtype: numpy.float32
        prediction:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          # dtype: numpy.float32
          rescale_dtype: numpy.uint8
  discriminator:
    _target_: cyto_dl.nn.discriminators.MultiScaleDiscriminator
    n_scales: 1
    input_nc: 2
    n_layers: 2
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 0.0003
      weight_decay: 0.0001
      betas:
      - 0.5
      - 0.99
    discriminator:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 0.0003
      weight_decay: 0.0001
      betas:
      - 0.5
      - 0.99
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.998
    discriminator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.998
  inference_args:
    sw_batch_size: 1
    roi_size: ${data._aux.patch_shape}
    overlap: 0.25
    mode: gaussian
callbacks:
logger:
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 1000
  accelerator: gpu
  devices:
  - 0
  check_val_every_n_epoch: 50
  deterministic: false
  detect_anomaly: false
  precision: 16
  num_sanity_val_steps: 1
paths:
  root_dir: .
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: true
  enforce_tags: false
  print_config: false
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
source_col: lr
target_col: hr
channel: 0
persist_cache: true
