working_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/validation/${deployment_name}
deployment_name: lf_dataset

local_run: True

steps:
    # - function: morflowgenesis.steps.split_czi.split_czi
    #   args:
    #       czi_path: //allen/aics/assay-dev/MicroscopyData/Leveille/2023/20230803/AD00004818_20230803_20X_L01.czi
    #       optical_control_path: //allen/aics/assay-dev/MicroscopyData/Leveille/2023/20230803/ZSD0_argo_20X_SLG-506_20230803_488.czi
    #       working_dir: ${working_dir}
    #       output_name: day3
    #       channels: -1
    #       dimension_order_out: CZYX
    #   step_type: "init"
    - function: morflowgenesis.steps.split_czi.split_czi
      args:
          czi_path: //allen/aics/assay-dev/MicroscopyData/John Paul/2023/20230804/20230804_T01_001.czi
          optical_control_path: //allen/aics/assay-dev/MicroscopyData/John Paul/2023/20230804/ZSD0_argo_20X_SLG-506_20230804_488.czi
          working_dir: ${working_dir}
          output_name: day4
          channels: -1
          dimension_order_out: CZYX
      step_type: "init"