working_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/validation/${deployment_name}
deployment_name: optimize_direct_seg_shape_high_semantic_loss

local_run: True

steps:
    - function: morflowgenesis.steps.image_object_from_csv.generate_objects
      args:
        csv_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/direct_seg_vs_nucmorph_tf_and_seg/manifest.csv
        working_dir: ${working_dir}
        source_column: lr
        non_source_columns: [hr]
      step_type: "init"


    # run segmentation from 20x
    - function: morflowgenesis.steps.run_cytodl_gather.run_cytodl
      args:
        output_name: 100x_lamin_seg
        input_step: generate_objects_lr
        # config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/optimize_shape_features/20x_lamin_to_100x_nucseg.yaml
        # run_id: b558528c285845f1813d34e106a9d566
        
        # config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/optimize_shape_features/20x_lamin_to_100x_nucseg_new_model.yaml
        # run_id: c9088a1d1a324b6795e02328f1590ca3

        config_path: //allen/aics/assay-dev/users/Benji/CurrentProjects/hydra_workflow/morflowgenesis/morflowgenesis/configs/optimize_shape_features/20x_lamin_to_100x_nucseg_high_semantic_loss.yaml
        run_id: 28968a81015b4dfb8f16f14c13f4c1c7 
      step_type: "gather"
    
    - function: morflowgenesis.steps.generate_thresholds.threshold
      args:
        output_name: thresh
        input_step: run_cytodl_100x_lamin_seg
        start: -4
        stop: 4
        step: 1
        label: True

    # watershed on real lamin
    - function: morflowgenesis.steps.segmentation_seeded_watershed.run_watershed
      args:
        output_name: real_lamin
        raw_input_step: generate_objects_hr
        seg_input_step: threshold_thresh_0.0
        mode: 'erosion'
        erosion: 5
        include_edge: False

    # create dataset with all real/tf lamin and direct/tf_watershed/lamin_watershed images
    - function: morflowgenesis.steps.single_cell_dataset.single_cell_dataset
      args:
        output_name: single_cell
        splitting_step: run_watershed_real_lamin
        raw_steps: [generate_objects_hr]
        seg_steps: [threshold_thresh.*, run_watershed_real_lamin]
        keep_lcc: True
        mask: False

    - function: morflowgenesis.steps.feature_calculation.calculate_features
      args:
        output_name: features
        input_step: single_cell_dataset_single_cell
        features:
            - height
            - volume

    - function: morflowgenesis.steps.plot.run_plot
      args:
        output_name: plot
        input_step: calculate_features_features
        features: [volume, height]
        label:
          segmentation_name: run_watershed_real_lamin
          description: 'Watershed on Real Lamin'
        pred:
          - segmentation_name: threshold_thresh*
            description: End to End Segmentation 
      step_type: 'gather'

