experiment_name: paired_dataset_tf_lf
run_name: lf
task_name: train
tags:
- dev
train: true
test: false
ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/paired_dataset_tf_lf/lf/2023-10-04_11-51-00/checkpoints/epoch_399.ckpt"
seed: 12345
data:
  _target_: cyto_dl.datamodules.data_dict.make_data_dict_dataloader
  data: null
  transforms:
  - _target_: monai.transforms.LoadImaged
    keys: ${source_col}
    reader:
    - _target_: cyto_dl.image.io.MonaiBioReader
      dimension_order_out: ZYX
      C: 0
  - _target_: monai.transforms.AddChanneld
    keys: ${source_col}
  - _target_: monai.transforms.ToTensord
    keys: ${source_col}
  - _target_: monai.transforms.NormalizeIntensityd
    keys: ${source_col}
  - _target_: cyto_dl.image.transforms.clip.Clipd
    keys: ${source_col}
    low: -7
    high: 7
    percentile: false
  _aux:
    patch_shape:
    - 32
    - 256
    - 256
  num_workers: 1
  batch_size: 1
  pin_memory: true
  persistent_workers: false
model:
  _target_: cyto_dl.models.im2im.MultiTaskIm2Im
  save_images_every_n_epochs: 1
  save_dir: ${paths.output_dir}
  x_key: ${source_col}
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: 1
    strides:
    - 1
    - 2
    - 2
    - 2
    kernel_size:
    - 3
    - 3
    - 3
    - 3
    upsample_kernel_size:
    - 2
    - 2
    - 2
    dropout: 0.0
    res_block: true
  task_heads: ${kv_to_dict:${model._aux._tasks}}
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 0.0001
      weight_decay: 0.0001
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.995
  inference_args:
    sw_batch_size: 1
    overlap: 0.25
    roi_size: ${data._aux.patch_shape}
    progress: True
  _aux:
    _tasks:
    - - ${target_col}
      - _target_: cyto_dl.nn.BaseHead
        loss:
          _target_: torch.nn.MSELoss
        postprocess:
          input:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            rescale_dtype: numpy.uint8
          prediction:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            dtype: numpy.float32
        save_raw: true
callbacks:
logger:
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 1000
  accelerator: gpu
  devices:
  - 0
  check_val_every_n_epoch: 50
  deterministic: false
  detect_anomaly: false
  precision: 16
  num_sanity_val_steps: 1
paths:
  root_dir: .
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: true
  enforce_tags: false
  print_config: false
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
source_col: bf
target_col: lamin
persist_cache: true
