channels: [1]
image_path: /allen/programs/allencell/data/proj0/94d/984/e94/01e/48f/6ab/046/00d/c84/1ed/49/AD00004745_20230720_AICS13_L01-01_AcquisitionBlock1_pt1.czi
name: starvation_scene3
scene: 3
timepoint_end: 570
